spring:
  application:
    name: homepage-config
  cloud:
    config:
      server:
        bootstrap: true
#        git:
#          uri: https://github.com/

server:
  port: 6000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/



