spring:
  application:
    name: homepage-euraka

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false #关闭自我保护模式
  client:
    #是否从eureka server 中获取注册信息
    fetch-registry: false
    #是否将自己注册到eureka server
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/